import type { WorkspacePermission } from "../core/permissions";

const operational: WorkspacePermission[] = ["workspace.access", "workspace.dashboard.view", "fortnite.access", "fortnite.dashboard.view", "players.view", "players.create", "players.edit", "players.archive", "players.view_performance", "players.performance.refresh", "players.performance.compare", "scouting.view", "scouting.create", "scouting.edit", "scouting.archive", "scouting.compare", "scouting.refresh", "scouting.notes.view", "scouting.notes.create", "streams.view", "streams.analytics.view", "streams.goals.view", "streams.compare", "overlays.view", "overlays.assign", "overlays.tokens.manage", "overlays.campaigns.view", "notifications.push.manage", "notifications.test", "calendar.view", "calendar.create", "calendar.edit", "tasks.view", "tasks.create", "tasks.edit", "tasks.assign", "meetings.view", "meetings.create", "meetings.edit", "contracts.view", "notifications.view", "notifications.manage_preferences"];

export const NOW_ROLE_PRESETS: Record<string, WorkspacePermission[]> = {
  ceo: ["workspace.access", "workspace.dashboard.view", "fortnite.access", "fortnite.dashboard.view", "players.view", "players.create", "players.edit", "players.archive", "players.view_performance", "players.performance.refresh", "players.performance.compare", "scouting.view", "scouting.create", "scouting.edit", "scouting.archive", "scouting.compare", "scouting.refresh", "scouting.notes.view", "scouting.notes.create", "scouting.notes.direction_view", "scouting.scores.manage", "analytics.export", "streams.view", "streams.manage", "streams.analytics.view", "streams.goals.view", "streams.goals.manage", "streams.compare", "overlays.view", "overlays.create", "overlays.edit", "overlays.publish", "overlays.assign", "overlays.tokens.manage", "overlays.campaigns.view", "overlays.campaigns.manage", "notifications.push.manage", "notifications.test", "calendar.view", "calendar.create", "calendar.edit", "calendar.delete", "tasks.view", "tasks.create", "tasks.edit", "tasks.assign", "tasks.delete", "meetings.view", "meetings.create", "meetings.edit", "contracts.view", "contracts.create", "contracts.edit", "contracts.view_financials", "finance.view", "notifications.view", "notifications.manage_preferences", "workspace.users.view", "workspace.users.manage", "workspace.roles.view", "workspace.roles.manage", "administration.access"],
  general_director: [...operational, "streams.manage", "streams.goals.manage", "overlays.create", "overlays.edit", "overlays.publish", "overlays.campaigns.manage", "scouting.notes.direction_view", "scouting.scores.manage", "analytics.export", "contracts.create", "contracts.edit", "contracts.view_financials", "finance.view", "workspace.users.view"],
  fortnite_director: [...operational, "streams.manage", "streams.goals.manage", "overlays.create", "overlays.edit", "overlays.publish", "overlays.campaigns.manage", "scouting.notes.direction_view", "scouting.scores.manage", "analytics.export", "contracts.create", "contracts.edit", "contracts.view_financials"],
  fortnite_manager: operational,
  player: ["workspace.access", "workspace.dashboard.view", "fortnite.access", "players.view", "players.view_performance", "calendar.view", "tasks.view", "notifications.view", "notifications.manage_preferences", "notifications.push.manage", "notifications.test"],
};
