import { MultiSeriesChart } from "@/components/workspace-charts";
import { WorkspaceHeader } from "@/components/workspace-shell";
import { createClient } from "@/lib/supabase/server";
import { requireWorkspacePermission } from "@/workspace/core/auth";
import { getMetricSeries } from "@/workspace/games/fortnite/data";
import type { MetricPeriod } from "@/workspace/games/fortnite/analytics";

const colors=["#e93585","#62d8ff","#a78bfa","#34d399","#fbbf24"];
export default async function Page({ searchParams }: { searchParams: Promise<{ ids?: string|string[]; period?: MetricPeriod }> }) {
  const access=await requireWorkspacePermission("players.performance.compare"); const filters=await searchParams; const selected=(Array.isArray(filters.ids)?filters.ids:filters.ids?[filters.ids]:[]).slice(0,5); const period=filters.period??"30d";
  const supabase=await createClient(); const {data:prospects}=await supabase.from("scouting_prospects").select("id,nickname,region,status").eq("organization_id",access.organizationId).neq("status","archived").order("nickname").limit(100);
  const series=selected.length?await getMetricSeries(access,{metric:"fortnite.pr",prospectIds:selected,period,maximumPoints:180}):[];
  const selectedProspects=prospects?.filter((prospect)=>selected.includes(prospect.id))??[];
  const latestMetrics=selected.length?(await supabase.from("player_performance_snapshots").select("prospect_id,metric_key,metric_value,currency,recorded_at").eq("organization_id",access.organizationId).in("prospect_id",selected).in("metric_key",["fortnite.pr","now.progression","now.consistency","now.recent_performance","fortnite.earnings_usd","fortnite.best_placement"]).order("recorded_at",{ascending:false}).limit(500)).data??[]:[];
  const value=(id:string,key:string)=>latestMetrics.find((metric)=>metric.prospect_id===id&&metric.metric_key===key)?.metric_value;
  return <><WorkspaceHeader eyebrow="Fortnite / Analytics" title="Player comparison" description="Comparez de 2 à 5 prospects sur des métriques normalisées et des snapshots réels."/><form className="mb-5 grid gap-3 rounded-xl border border-white/8 bg-white/[.025] p-4 md:grid-cols-[1fr_auto_auto]"><select multiple name="ids" defaultValue={selected} aria-label="Players to compare" className="min-h-32 rounded-lg border border-white/10 bg-black/30 p-2 text-sm">{prospects?.map(prospect=><option key={prospect.id} value={prospect.id}>{prospect.nickname} · {prospect.region??"N/A"}</option>)}</select><select name="period" defaultValue={period} className="h-10 rounded-lg bg-black/30 px-3 text-sm">{["7d","30d","90d","6m","1y","all"].map(value=><option key={value}>{value}</option>)}</select><button className="h-10 rounded-lg bg-[#e93585] px-4 text-sm font-bold">Compare</button></form>{selected.length<2?<div className="rounded-xl border border-dashed border-white/10 p-10 text-center text-white/50">Sélectionnez entre 2 et 5 joueurs.</div>:<><MultiSeriesChart title={`Power Ranking · ${period}`} series={series.map((item,index)=>({id:item.subjectId,label:selectedProspects.find((prospect)=>prospect.id===item.subjectId)?.nickname??"Player",color:colors[index%colors.length],points:item.points.map((point)=>({label:point.recordedAt,value:point.value}))}))}/><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{selectedProspects.map(prospect=><article key={prospect.id} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><h2 className="font-bold">{prospect.nickname}</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-sm">{[["PR","fortnite.pr"],["Progression","now.progression"],["NOW Score","now.scouting_score"],["Consistency","now.consistency"],["Recent performance","now.recent_performance"],["Earnings USD","fortnite.earnings_usd"],["Best placement","fortnite.best_placement"]].map(([label,key])=><div key={key}><dt className="text-xs text-white/35">{label}</dt><dd>{value(prospect.id,key)==null?"N/A":Number(value(prospect.id,key)).toLocaleString()}</dd></div>)}</dl></article>)}</div></>}</>;
}
