import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import type { PerformanceProvider } from "./performance-provider";
import { FortniteTrackerProvider } from "./fortnite-tracker-provider";
import { computeProgression } from "./computed-metrics";
import { getMetricDefinition } from "./metric-registry";
import { computeScoutingScore, type ScoreCriterion, type MissingMetricStrategy } from "./scoring";

export type SyncPolicy = { batchSize: number; activeIntervalMinutes: number; scoutingIntervalMinutes: number };
export function getSyncPolicy(env: NodeJS.ProcessEnv = process.env): SyncPolicy {
  const number = (value:string|undefined,fallback:number)=>Number.isSafeInteger(Number(value))&&Number(value)>0?Number(value):fallback;
  return {batchSize:number(env.FORTNITE_TRACKER_SYNC_BATCH_SIZE,20),activeIntervalMinutes:number(env.FORTNITE_TRACKER_SYNC_INTERVAL_ACTIVE,60),scoutingIntervalMinutes:number(env.FORTNITE_TRACKER_SYNC_INTERVAL_SCOUTING,360)};
}

async function recomputeProspectScores(supabase: ReturnType<typeof createAdminClient>, organizationId: string, prospectId: string, computedAt: string) {
  const { data: profiles } = await supabase.from("scouting_score_profiles").select("id,version,missing_metric_strategy,scouting_score_criteria(metric_key,weight,direction,minimum,maximum,is_required)").eq("organization_id",organizationId).eq("is_active",true);
  for (const profile of profiles ?? []) {
    const rawCriteria=profile.scouting_score_criteria as unknown as Array<{metric_key:string;weight:number;direction:"higher"|"lower";minimum:number|null;maximum:number|null;is_required:boolean}>;
    if (!rawCriteria.length || rawCriteria.some((item)=>item.minimum===null||item.maximum===null)) continue;
    const keys=rawCriteria.map((item)=>item.metric_key);const {data:snapshots}=await supabase.from("player_performance_snapshots").select("metric_key,metric_value,recorded_at").eq("organization_id",organizationId).eq("prospect_id",prospectId).in("metric_key",keys).order("recorded_at",{ascending:false}).limit(keys.length*10);const values:Record<string,number>={};for(const snapshot of snapshots??[])if(values[snapshot.metric_key]===undefined)values[snapshot.metric_key]=Number(snapshot.metric_value);
    const criteria:ScoreCriterion[]=rawCriteria.map((item)=>({metricKey:item.metric_key,weight:Number(item.weight),direction:item.direction==="higher"?"higher_is_better":"lower_is_better",minimum:Number(item.minimum),maximum:Number(item.maximum),required:item.is_required}));let result;try{result=computeScoutingScore(criteria,values,profile.missing_metric_strategy as MissingMetricStrategy);}catch{continue;}
    await supabase.from("scouting_score_snapshots").insert({organization_id:organizationId,prospect_id:prospectId,profile_id:profile.id,profile_version:profile.version,score:result.score,is_complete:result.complete,available_criteria:result.availableCriteria,total_criteria:result.totalCriteria,explanation:result.explanation,computed_at:computedAt});if(result.score!==null)await supabase.from("player_performance_snapshots").insert({organization_id:organizationId,prospect_id:prospectId,provider:"manual",metric_key:"now.scouting_score",metric_value:result.score,recorded_at:computedAt,metadata:{profile_id:profile.id,profile_version:profile.version}});
  }
}

export async function syncTrackedFortnitePlayers(organizationId: string, provider: PerformanceProvider = new FortniteTrackerProvider(), policy = getSyncPolicy()) {
  const supabase=createAdminClient();const now=new Date();const{data:links}=await supabase.from("fortnite_player_provider_links").select("id,subject_type,workspace_player_id,prospect_id,provider_player_id,platform").eq("organization_id",organizationId).eq("provider","fortnite_tracker").or(`next_sync_at.is.null,next_sync_at.lte.${now.toISOString()}`).limit(policy.batchSize);const summary={processed:0,succeeded:0,failed:0,rateLimited:false};
  for(const link of links??[]){summary.processed+=1;const started=Date.now();const{data:run}=await supabase.from("fortnite_sync_runs").insert({organization_id:organizationId,provider_link_id:link.id,operation:"refresh",status:"running"}).select("id").single();await supabase.from("fortnite_player_provider_links").update({sync_status:"syncing"}).eq("id",link.id);const result=await provider.refreshPlayer(link.provider_player_id,link.platform??"epic");if(result.status!=="available"){const status=result.status==="rate_limited"?"rate_limited":result.status==="not_configured"||result.status==="not_supported"?"provider_unavailable":"failed";summary.failed+=1;summary.rateLimited ||= result.status==="rate_limited";await supabase.from("fortnite_player_provider_links").update({sync_status:status,next_sync_at:new Date(Date.now()+policy.scoutingIntervalMinutes*60_000).toISOString()}).eq("id",link.id);if(run)await supabase.from("fortnite_sync_runs").update({status,error_code:result.status,completed_at:new Date().toISOString(),duration_ms:Date.now()-started}).eq("id",run.id);if(summary.rateLimited)break;continue;}
    let written=0;for(const metric of result.data.metrics){const subjectColumn=link.subject_type==="prospect"?"prospect_id":"player_id";const subjectId=link.prospect_id??link.workspace_player_id!;const{data:latest}=await supabase.from("player_performance_snapshots").select("metric_value,recorded_at").eq("organization_id",organizationId).eq(subjectColumn,subjectId).eq("metric_key",metric.key).order("recorded_at",{ascending:false}).limit(2);const newest=latest?.[0];if(!(newest&&Number(newest.metric_value)===metric.value&&new Date(result.data.capturedAt).getTime()-new Date(newest.recorded_at).getTime()<300_000)){const{error}=await supabase.from("player_performance_snapshots").insert({organization_id:organizationId,[subjectColumn]:subjectId,provider:"fortnite_tracker",metric_key:metric.key,metric_value:metric.value,currency:metric.currency,recorded_at:result.data.capturedAt,metadata:{region:metric.region,season:metric.season}});if(!error)written+=1;}const previous=latest?.at(-1);const definition=getMetricDefinition(metric.key);if(previous&&definition&&definition.direction!=="neutral"){const progression=computeProgression(Number(previous.metric_value),metric.value,definition.direction);if(progression!==null)await supabase.from("player_performance_snapshots").insert({organization_id:organizationId,[subjectColumn]:subjectId,provider:"manual",metric_key:"now.progression",metric_value:progression,recorded_at:result.data.capturedAt,metadata:{basis_metric:metric.key,method:"percentage_change_v1"}});}}
    summary.succeeded+=1;const interval=link.subject_type==="workspace_player"?policy.activeIntervalMinutes:policy.scoutingIntervalMinutes;await supabase.from("fortnite_player_provider_links").update({sync_status:"successful",last_synced_at:result.data.capturedAt,next_sync_at:new Date(Date.now()+interval*60_000).toISOString()}).eq("id",link.id);if(link.prospect_id){await supabase.from("scouting_prospects").update({sync_status:"successful",last_synced_at:result.data.capturedAt,sync_error_code:null}).eq("id",link.prospect_id);await recomputeProspectScores(supabase,organizationId,link.prospect_id,result.data.capturedAt);}if(run)await supabase.from("fortnite_sync_runs").update({status:"successful",metrics_written:written,completed_at:new Date().toISOString(),duration_ms:Date.now()-started}).eq("id",run.id);
  }
  return summary;
}
