import type{LiveStream,StreamProvider,StreamProviderResult,StreamUser}from"../core/types.ts";import{getTwitchConfig,type TwitchConfig}from"./config.ts";
type Token={value:string;expiresAt:number};let appToken:Token|null=null;export function resetTwitchTokenCache(){appToken=null}
export class TwitchProvider implements StreamProvider{private config:TwitchConfig;private fetcher:typeof fetch;constructor(config:TwitchConfig=getTwitchConfig(),fetcher:typeof fetch=fetch){this.config=config;this.fetcher=fetcher}
 private async token(force=false):Promise<StreamProviderResult<string>>{if(!this.config.clientId||!this.config.clientSecret)return{status:"not_configured",message:"Twitch n’est pas configuré."};if(!force&&appToken&&appToken.expiresAt>Date.now()+60_000)return{status:"available",data:appToken.value};const body=new URLSearchParams({client_id:this.config.clientId,client_secret:this.config.clientSecret,grant_type:"client_credentials"});const result=await this.raw("https://id.twitch.tv/oauth2/token",{method:"POST",body},false);if(result.status!=="available")return result;const payload=result.data as{access_token?:string;expires_in?:number};if(!payload.access_token)return{status:"provider_error",message:"Réponse OAuth Twitch invalide."};appToken={value:payload.access_token,expiresAt:Date.now()+(payload.expires_in??3600)*1000};return{status:"available",data:appToken.value}}
 private async helix(path:string,init:RequestInit={},retryToken=true):Promise<StreamProviderResult<unknown>>{const token=await this.token();if(token.status!=="available")return token;const result=await this.raw(`https://api.twitch.tv/helix${path}`,{...init,headers:{"Client-Id":this.config.clientId!,Authorization:`Bearer ${token.data}`,"Content-Type":"application/json",...(init.headers??{})}},true);if(result.status==="provider_error"&&result.message==="unauthorized"&&retryToken){appToken=null;await this.token(true);return this.helix(path,init,false)}return result}
 private async raw(url:string,init:RequestInit,helix:boolean):Promise<StreamProviderResult<unknown>>{for(let attempt=0;attempt<=this.config.maxRetries;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.config.timeoutMs);try{const response=await this.fetcher(url,{...init,signal:controller.signal,cache:"no-store"});clearTimeout(timer);if(response.status===401)return{status:"provider_error",message:"unauthorized"};if(response.status===404)return{status:"not_found",message:"Compte Twitch introuvable."};const retryAfter=Number(response.headers.get("ratelimit-reset"));if(response.status===429&&attempt===this.config.maxRetries)return{status:"rate_limited",message:"Quota Twitch atteint.",retryAfterSeconds:Number.isFinite(retryAfter)?Math.max(0,retryAfter-Math.floor(Date.now()/1000)):undefined};if((response.status===429||response.status>=500)&&attempt<this.config.maxRetries){await new Promise(r=>setTimeout(r,250*2**attempt));continue}if(!response.ok)return{status:"provider_error",message:helix?"Twitch API est indisponible.":"Authentification Twitch impossible."};if(response.status===204)return{status:"available",data:{}};try{return{status:"available",data:await response.json()}}catch{return{status:"provider_error",message:"Réponse Twitch invalide."}}}catch{clearTimeout(timer);if(attempt===this.config.maxRetries)return{status:"provider_error",message:"Twitch API est temporairement indisponible."}}}return{status:"provider_error",message:"Twitch API est indisponible."}}
 async resolveUser(login:string){const r=await this.helix(`/users?login=${encodeURIComponent(login)}`);if(r.status!=="available")return r;const u=(r.data as{data?:Array<{id:string;login:string;display_name:string;profile_image_url?:string}>}).data?.[0];return u?{status:"available",data:{id:u.id,login:u.login,displayName:u.display_name,profileImageUrl:u.profile_image_url}}as const:{status:"not_found",message:"Compte Twitch introuvable."}as const}
 async getUsers(ids:string[]){if(!ids.length)return{status:"available",data:[]}as StreamProviderResult<StreamUser[]>;const r=await this.helix(`/users?${ids.slice(0,100).map(id=>`id=${encodeURIComponent(id)}`).join("&")}`);if(r.status!=="available")return r;return{status:"available",data:((r.data as{data?:Array<{id:string;login:string;display_name:string;profile_image_url?:string}>}).data??[]).map(u=>({id:u.id,login:u.login,displayName:u.display_name,profileImageUrl:u.profile_image_url}))}as StreamProviderResult<StreamUser[]>}
 async getStreams(ids:string[]){if(!ids.length)return{status:"available",data:[]}as StreamProviderResult<LiveStream[]>;const r=await this.helix(`/streams?${ids.slice(0,100).map(id=>`user_id=${encodeURIComponent(id)}`).join("&")}`);if(r.status!=="available")return r;return{status:"available",data:((r.data as{data?:Array<Record<string,unknown>>}).data??[]).map(s=>({id:String(s.id),userId:String(s.user_id),userLogin:String(s.user_login),userName:String(s.user_name),gameId:String(s.game_id??""),gameName:String(s.game_name??""),title:String(s.title??""),viewerCount:Number(s.viewer_count),startedAt:String(s.started_at),thumbnailUrl:String(s.thumbnail_url??"")}))}as StreamProviderResult<LiveStream[]>}
 async createEventSubSubscription(type:"stream.online"|"stream.offline",userId:string){if(!this.config.eventSubCallbackUrl||!this.config.eventSubSecret)return{status:"not_configured",message:"EventSub n’est pas configuré."}as const;const r=await this.helix("/eventsub/subscriptions",{method:"POST",body:JSON.stringify({type,version:"1",condition:{broadcaster_user_id:userId},transport:{method:"webhook",callback:this.config.eventSubCallbackUrl,secret:this.config.eventSubSecret}})});if(r.status!=="available")return r;const x=(r.data as{data?:Array<{id:string;status:string}>}).data?.[0];return x?{status:"available",data:x}as const:{status:"provider_error",message:"Réponse EventSub invalide."}as const}
 async deleteEventSubSubscription(id:string){const r=await this.helix(`/eventsub/subscriptions?id=${encodeURIComponent(id)}`,{method:"DELETE"});return r.status==="available"?{status:"available" as const,data:true as const}:r as StreamProviderResult<true>}
 async listEventSubSubscriptions(){const r=await this.helix("/eventsub/subscriptions");if(r.status!=="available")return r;return{status:"available",data:(r.data as{data?:Array<{id:string;type:string;status:string}>}).data??[]}as const}}
