import { MultiSeriesChart } from "@/components/workspace-charts";
import { WorkspaceHeader } from "@/components/workspace-shell";
import { createClient } from "@/lib/supabase/server";
import { requireWorkspacePermission } from "@/workspace/core/auth";
import { getMetricSeries } from "@/workspace/games/fortnite/data";
import type { MetricPeriod } from "@/workspace/games/fortnite/analytics";
import { FORTNITE_METRICS } from "@/workspace/games/fortnite/metric-registry";
const colors=["#e93585","#62d8ff","#a78bfa","#34d399","#fbbf24","#fb7185","#818cf8","#2dd4bf","#f97316","#c084fc"];
export default async function Page({searchParams}:{searchParams:Promise<{source?:"roster"|"scouting"|"all";metric?:string;period?:MetricPeriod}>}){const access=await requireWorkspacePermission("players.view_performance");const filters=await searchParams;const source=filters.source??"all";const metric=FORTNITE_METRICS.some(item=>item.key===filters.metric)?filters.metric!:"fortnite.pr";const period=filters.period??"30d";const supabase=await createClient();const [{data:players},{data:prospects}]=await Promise.all([supabase.from("workspace_player_profiles").select("id,roster_members(display_name)").eq("organization_id",access.organizationId).eq("is_archived",false).limit(50),supabase.from("scouting_prospects").select("id,nickname").eq("organization_id",access.organizationId).neq("status","archived").limit(50)]);const playerIds=source!=="scouting"?players?.map(item=>item.id):undefined;const prospectIds=source!=="roster"?prospects?.map(item=>item.id):undefined;const result=await getMetricSeries(access,{metric,playerIds,prospectIds,period,maximumPoints:180});const label=(id:string)=>{const player=players?.find(item=>item.id===id);return (player?.roster_members as unknown as {display_name?:string}|null)?.display_name??prospects?.find(item=>item.id===id)?.nickname??"Player"};return <><WorkspaceHeader eyebrow="Fortnite / Performance" title="Performance analytics" description="Séries agrégées côté serveur, périodes bornées et aucun historique inventé."/><form className="mb-5 flex flex-wrap gap-2"><select name="source" defaultValue={source} className="rounded-lg bg-black/30 p-2 text-sm"><option value="roster">Roster NOW</option><option value="scouting">Scouting</option><option value="all">All</option></select><select name="metric" defaultValue={metric} className="rounded-lg bg-black/30 p-2 text-sm">{FORTNITE_METRICS.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select><select name="period" defaultValue={period} className="rounded-lg bg-black/30 p-2 text-sm">{["7d","30d","90d","6m","1y","all"].map(value=><option key={value}>{value}</option>)}</select><button className="rounded-lg border border-white/10 px-4 text-sm">Apply</button></form><MultiSeriesChart title={`${FORTNITE_METRICS.find(item=>item.key===metric)?.label} · ${period}`} series={result.slice(0,10).map((item,index)=>({id:item.subjectId,label:label(item.subjectId),color:colors[index%colors.length],points:item.points.map(point=>({label:point.recordedAt,value:point.value}))}))}/><p className="mt-3 text-xs text-white/35">Top 10 séries affichées. Utilisez Compare pour une sélection précise de 2 à 5 profils.</p></>}
