import assert from "node:assert/strict";
import test from "node:test";
import { TrackerHttpClient } from "../../src/workspace/games/fortnite/tracker-http-client.ts";
import { normalizeTrackerEnvelope, TrackerSchemaError } from "../../src/workspace/games/fortnite/tracker-normalizer.ts";
const config=(overrides={})=>({apiKey:"super-secret",baseUrl:"https://partner.example/",endpoints:{profile:"/profiles/{playerId}"},timeoutMs:30,maxRetries:0,cacheTtlMs:1000,minimumRequestIntervalMs:1,...overrides});
const response=(status,payload,headers={})=>new Response(payload===undefined?undefined:JSON.stringify(payload),{status,headers:{"content-type":"application/json",...headers}});

test("provider reports missing API key and base URL",async()=>{assert.equal((await new TrackerHttpClient(config({apiKey:undefined})).request("profile",{playerId:"x"})).status,"not_configured");assert.equal((await new TrackerHttpClient(config({baseUrl:undefined})).request("profile",{playerId:"x"})).status,"not_configured")});
test("provider does not retry or leak secrets for 401, 403 and 404",async()=>{for(const status of [401,403,404]){let calls=0;const result=await new TrackerHttpClient(config(),async()=>{calls++;return response(status,{secret:"raw"})}).request("profile",{playerId:"x"});assert.equal(calls,1);assert.ok(["provider_error","not_found"].includes(result.status));assert.doesNotMatch(JSON.stringify(result),/super-secret|raw|TRN-Api-Key/)}});
test("provider classifies 429 and retries transient 500",async()=>{const limited=await new TrackerHttpClient(config(),async()=>response(429,{}, {"retry-after":"4"})).request("profile",{playerId:"x"});assert.equal(limited.status,"rate_limited");if(limited.status==="rate_limited")assert.equal(limited.retryAfterSeconds,4);let calls=0;const recovered=await new TrackerHttpClient(config({maxRetries:1}),async()=>{calls++;return calls===1?response(500,{}):response(200,{player:{id:"1",name:"A"}})}).request("profile",{playerId:"x"});assert.equal(recovered.status,"available");assert.equal(calls,2)});
test("provider handles timeout and invalid JSON",async()=>{const timeout=await new TrackerHttpClient(config(),(_url,{signal}={})=>new Promise((_resolve,reject)=>signal?.addEventListener("abort",()=>reject(new DOMException("Timeout","AbortError"))))).request("profile",{playerId:"x"});assert.equal(timeout.status,"provider_error");const invalid=await new TrackerHttpClient(config(),async()=>new Response("not-json",{status:200})).request("profile",{playerId:"x"});assert.equal(invalid.status,"provider_error")});
test("normalizer rejects unexpected schema and normalizes contract envelope",()=>{assert.throws(()=>normalizeTrackerEnvelope({unexpected:true}),TrackerSchemaError);const result=normalizeTrackerEnvelope({player:{id:"p1",name:"Nova",platform:"epic"},metrics:[{key:"fortnite.pr",value:1234}],results:[]},new Date("2026-01-01T00:00:00Z"));assert.equal(result.identity.nickname,"Nova");assert.equal(result.metrics[0].value,1234);assert.equal(result.capturedAt,"2026-01-01T00:00:00.000Z")});
import { parseTrackerProfileUrl, normalizeNickname } from "../../src/workspace/games/fortnite/tracker-link.ts";
test("Tracker URL parser accepts known hosts and blocks SSRF inputs",()=>{const tracker=parseTrackerProfileUrl("https://tracker.gg/fortnite/profile/epic/Player%20One");assert.equal(tracker?.platform,"epic");assert.equal(tracker?.username,"Player One");assert.match(tracker?.normalizedUrl??"",/^https:\/\/tracker\.gg\//);assert.equal(parseTrackerProfileUrl("https://evil.example/profile/epic/player"),null);assert.equal(parseTrackerProfileUrl("http://tracker.gg/fortnite/profile/epic/player"),null);assert.equal(parseTrackerProfileUrl("https://user:pass@tracker.gg/fortnite/profile/player"),null);assert.equal(normalizeNickname("  Ｎova "),"nova")});
